<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    //
    protected $fillable = ['id', 'title', 'parent', 'path'];

    public function delete()
    {
        //

        self::where('parent', $this->id)->delete();
        return parent::delete(); // TODO: Change the autogenerated stub
    }


}
